### ISSUE TITLE
CommandBox does not install browsers drivers in the commandbox_home

### ISSUE THREAD

**Issue by phoenixfangor** [commandbox-modules/commandbox-cbplaywright#3]
**Current:**
I set the commandbox_home in the commandbox.properties file in the same folder as box.exe
I installed commandbox-cbplaywright in through CommandBox.
When I run `playwright install chromium` in CommandBox, these drivers are still installed in the default C:\Users\_username_\AppData\Local\ms-playwright\ folder.
**Expected:** I would expect these drivers to be installed in the commandbox_home folder.

**Comment by bdw429s** [comment]
@phoenixfangor If the playwright library didn't install its browsers into the CommandBox home before, what makes you think it would do so now?

**Comment by phoenixfangor** [comment]
> @phoenixfangor If the playwright library didn't install its browsers into the CommandBox home before, what makes you think it would do so now?

That's a good point. I needed to look at the Playwright docs, here: https://playwright.dev/java/docs/browsers#managing-browser-binaries

**Comment by phoenixfangor** [comment]
So, the real issue is that I do have the PLAYWRIGHT_BROWSERS_PATH environment variable set, and the playwright CLI "bridge" is not respecting THAT.
